update:
  # Seconds between checks for Residence updates
  period: 300
layer:
  name: Towny
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
  # Show shop blocks with their own fill color
  showShops: false
  # Show arena blocks with their own fill color
  showArenas: false
  # Show embassy blocks with their own fill color
  showEmbassies: true
  # Show wild blocks with their own fill color
  showWilds: false
visibility-by-town: true
visibility-by-nation: true
dynamic-nation-colors: true
dynamic-town-colors: true
infowindow: <div class="infowindow"> <span style="font-size:160%;">%regionname% </span><br
  /> Nation&#58; <span style="font-weight:bold;">%nation%</span><br/> Occupier&#58;
  <span style="font-weight:bold;"> %occupier%</span><br/> Mayor&#58; <span style="font-weight:bold;">%playerowners%</span><br
  /> Resources&#58; <span style="font-weight:bold;">%town_resources%</span> </div>
regionstyle:
  strokeColor: '#FF0000'
  strokeOpacity: 0.6
  strokeWeight: 3
  fillColor: '#FF0000'
  fillOpacity: 0.25
  homeicon: none
  capitalicon: king
  fillColorShops: '#0000FF'
  fillColorArenas: '#FF00FF'
  fillColorEmbassies: '#00FFFF'
  fillColorWilds: '#00FF00'
  boost: false
visibleregions: []
hiddenregions: []
custstyle:
  customregion1:
    strokeColor: '#00FF00'
    y: 64
  customregion2:
    strokeColor: '#007F00'
    y: 64
    boost: false
nationstyle:
  NationOfBlue:
    strokeColor: '#0000FF'
    fillColor: '#0000FF'
    boost: false
  _none_:
    homeicon: none
chat:
  sendlogin: true
  sendquit: true
  format: '&color;2[WEB] %playername%: &color;f%message%'
